'use client';
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {MenuFooter} from "@/components/menu-footer";
import {PageTitle} from "@/components/page-title";
import {SpotifyApi} from "@spotify/web-api-ts-sdk";
import {useEffect} from "react";
import {Scopes} from "@/scopes";
import {HistoryProvider} from '@/contexts/History'

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

//export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
//};

const spotifyClientId = process.env.NEXT_PUBLIC_AUTH_SPOTIFY_ID!;

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    useEffect(() => {
        async function setUpAuth() {
            console.log('setting sdk now');
            globalThis.sdk = SpotifyApi.withUserAuthorization(spotifyClientId, "http://localhost:3000/home", Scopes.all);
            await globalThis.sdk.authenticate().then((authRes) => console.log(authRes));
        }

        setUpAuth();
    }, [])

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <HistoryProvider>
            <div
                className="grid grid-rows-[20px_660px_20px] justify-items-center min-h-screen p-8 pb-10 gap-8 sm:p-20 font-[family-name:var(--font-geist-sans)]">

                <PageTitle/>
                <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
                    {children}
                </main>
                <footer style={{marginTop: '-20px'}}
                        className="row-start-3 flex gap-6 flex-wrap items-center justify-center border-t-2 border-t-gray-500 pt-3">
                    <MenuFooter/>
                </footer>
            </div>
        </HistoryProvider>
        </body>
        </html>
    );
}
